server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.banking.discovery: DEBUG
  file:
    name: logs/app.log
